runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyCBC0n9nqXGu1e3gXhkA3u-55GDUORCul4 

handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
- ^LICENSE
